<?php

/**
 * PluginEnqueteAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEnqueteAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEnqueteAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEnqueteAnswer');
    }
}