<?php

/**
 * PluginEnqueteQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEnqueteQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEnqueteQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEnqueteQuestion');
    }
}