<?php

/**
 * PluginEnqueteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEnqueteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEnqueteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEnquete');
    }
}