<?php

/**
 * PluginEnqueteCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEnqueteCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEnqueteCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEnqueteComment');
    }
}